### ISSUE TITLE
Move to `main` branch

### ISSUE THREAD

**Issue by toastal** [purs-nix/purs-nix#11]
Almost everything in `purescript-contrib` uses `main` as the default branch--and it's a more inclusive term.

https://www.r-bloggers.com/2020/07/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by ursi** [comment]
My preference is to follow the `git` default branch name. Should that be changed, we can revisit this.

**Comment by ursi** [comment]
To be clear, I'm fine with leaving the codeberg mirror on `main` since you set that up.

**Comment by toastal** [comment]
`main` is the default on GitHub, GitLab, Codeberg which meant when I added the repo on Codeberg it reminded me to check what the PureScript community was doing. However, you can't have two different names if you want a true, easy-to-use mirror (hence the docs I opened saying to call *both* `origin` so they go together).
