### ISSUE TITLE
Add an override system

### ISSUE THREAD

**Issue by srid** [purs-nix/purs-nix#24]
Use `makeExtensible` and `extends` to allow overriding the official package set.

Eventually, consider specifying local packages in `overrides` as well.

**Comment by srid** [comment]
We may want to expose the `ps` atttrset via `passthru` as well.

Example: 

```nix
      packages.array =
        (config.purs-nix.build {
          name = "array";
          src.path = ./.;
          info = { inherit dependencies; };
        }).overrideAttrs (old: {
          passthru = old.passthru // {
            purs-nix = {
              inherit ps;
              command = ps.command { name = "pn-array"; };
            };
          };
        });
```

and then used as:

```nix
      checks = {
        array-test = self'.packages.array.purs-nix.ps.test.check { };
      };

      devShells.array = pkgs.mkShell {
        buildInputs = [ self'.packages.array.purs-nix.command ];
      };
```

**Comment by srid** [comment]
Spoke over call. Rough notes below:


https://github.com/NixOS/nixpkgs/blob/master/lib/fixed-points.nix

```nix
let obj = makeExtensible (self: {})
let officialPackageSet = obj.extend(self: super: {
    prelude = purs-nix.build {..};
});
pkgset = officialPackageSet.extend (self: super: {
    # TODO: put more-pkgs.nix
    markdown = purs-nix.build (fetchGithub (...))
    # TODO: local packages
    foo = purs-nix.build { root = ./lib/foo; ... };

})
```

I'll see if I can find a comparable Haskell example.

**Comment by srid** [comment]
How it looks in Haskell: https://github.com/srid/haskell-multi-nix/blob/0702e3f4ad75a2075a7f0e0d7988aa29d24a6a65/flake.nix#L12-L24

Explanation: https://github.com/srid/haskell-multi-nix#explanation

**Comment by ursi** [comment]
done in 0f4650e74928e0deefcf806e13c0656462d046f8
