### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by srid** [purs-nix/purs-nix#29]
In parallel to (and independent of) #23 per https://hercules-ci.com/github/purs-nix/purs-nix/jobs/83 we can see that `./test` checks are broken.

For example,

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3998/194169923-be638e62-36a3-44cc-bf8e-880fafb277a1.png">

I imagine they can be resolved independent of #23

**Comment by ursi** [comment]
This is on a dummy branch that was just pushed to try out some code.

**Comment by srid** [comment]
Oh right.
