### ISSUE TITLE
`master` branch to contain multiple PureScript versions

### ISSUE THREAD

**Issue by srid** [purs-nix/purs-nix#31]
## Current approach

When adding a feature to purs-nix, create a PR to merge it to `master` _and then_ create another PR to merge it to `ps-0.14` and so on.

## Proposed approach

Get rid of versioned branches, like `ps-0.14`, and keep _all_ PureScript versions (0.15, 0.14) in the `master` branch of purs-nix ... because of the benefit of not needing to create >1 PRs like in the current approach above.

**Comment by ursi** [comment]
I understand wanting to merge these, and at some point in the future they might be, but in the mean time, no one needs to make a pr for both branches. I will keep 0.14 up with master myself.
