### ISSUE TITLE
Added packages require extra attributes, not documented

### ISSUE THREAD

**Issue by peterbecich** [purs-nix/purs-nix#34]
I have a Nix Flake using `purs-nix`: https://github.com/peterbecich/halogen-chess/blob/master/flake.nix

The Purescript code is built with:
```
nix build .#purescriptBundle 
```

For this project there are two dependencies, `argonaut-aeson-generic` and `foreign-generic`, which are not in the default package set, so following these instructions https://github.com/purs-nix/purs-nix/blob/master/docs/adding-packages.md I have defined them manually here:
https://github.com/peterbecich/halogen-chess/blob/9ed15cfc2ca503077d6abbfaccfe03c7d9157829/flake.nix#L51-L111

These two objects `argonaut-aeson-generic` and `foreign-generic` each have two extra attributes which appear to be necessary:
- `purs-nix-info.name`
- `purs-nix-info.dependencies`: This is redundant to the documented required attribute `info.dependencies`

Without `purs-nix-info.name` I see:
```
error: attribute 'name' missing

       at /nix/store/l5zpai4gi760giiv5y7ixxdkya5ajrlj-source/purs-nix.nix:73:30:

           72|                 {}
           73|                 (sort (a: b: a.purs-nix-info.name < b.purs-nix-info.name) deps);
             |                              ^
           74|           in
```
and without `purs-nix-info.dependencies` I see:
```
error: attribute 'dependencies' missing

       at /nix/store/l5zpai4gi760giiv5y7ixxdkya5ajrlj-source/purs-nix.nix:65:24:

           64|                        (acc // { ${name} = dep; })
           65|                        dep.purs-nix-info.dependencies
             |                        ^
           66|                    else
```

Should the `name` attribute be mentioned in the **Package Set: Git** section of https://github.com/purs-nix/purs-nix/blob/master/docs/adding-packages.md ?

Can the redundant `purs-nix-info.dependencies` be made unnecessary?

```
git clone https://github.com/peterbecich/halogen-chess.git
```

------------------

There is a third error, off topic from this issue, which appears after `name` and `dependencies` are fixed. https://github.com/purs-nix/purs-nix/issues/35

-----------------

Thanks

**Comment by ursi** [comment]
Check out these three ways of doing what you want and let me know if you need any help.
- [overlays](https://github.com/purs-nix/purs-nix/blob/66427405d2a3e0c2491646a6efc1716ce3731f3d/docs/modifying-package-set.md)
- [build-set](https://github.com/purs-nix/purs-nix/blob/66427405d2a3e0c2491646a6efc1716ce3731f3d/docs/adding-packages.md#build-set)
- [build](https://github.com/purs-nix/purs-nix/blob/66427405d2a3e0c2491646a6efc1716ce3731f3d/docs/adding-packages.md#build)

**Comment by peterbecich** [comment]
Thanks, I was using this incorrectly. This works:
https://github.com/peterbecich/halogen-chess/blob/2d881da34f513f79da479d804b7eb740d0dcc887/flake.nix#L52-L96

**Comment by peterbecich** [comment]
@ursi , one question

I am looking at this commit https://github.com/peterbecich/halogen-chess/tree/2d881da34f513f79da479d804b7eb740d0dcc887 and using `nix develop`.
The project is not yet compiled; I have deleted `output`, `result`, etc.

`purs-nix bundle` fails with this error:

```
$ purs-nix bundle 
.
.
.
lots of building
.
.
.
✘ [ERROR] Could not resolve "./output/Main/index.js"

    <stdin>:1:21:
      1 │ import { main } from "./output/Main/index.js"; main()
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~
```


However, `spago build` fixes the error.

```
$ spago build
.
.
.
more building
.
.
success


$ purs-nix bundle
.
.
.
more building
.
.
Bundling complete
```


Do you know why this depends on Spago? I must have set up the Flake incorrectly. It appears to me Spago is providing the missing `output/Main/index.js` from outside the Nix process. How can the Flake be configured so the entire project can be built only with `purs-nix bundle`?

**Comment by ursi** [comment]
https://github.com/peterbecich/halogen-chess/blob/2d881da34f513f79da479d804b7eb740d0dcc887/flake.nix#L130-L131
This is the problem. If you use nix path values like this, they cannot be added to the purs-nix command by default, so you'll need to respecify them as strings in the `srcs` argument of `ps.command`. Alternatively, if you use `dir = ./.` with `srcs = [ "src" "app" ]`, purs-nix can use that information to build the command properly.

**Comment by peterbecich** [comment]
Thanks, you're correct, `purs-nix bundle` works now without `spago`:
https://github.com/peterbecich/halogen-chess/blob/2cc5f898950f2f1f3c1074fe0e64228125b8e480/flake.nix#L130-L131
