### ISSUE TITLE
whitespace character included in `official-package-set` `dependencies` lists

### ISSUE THREAD

**Issue by peterbecich** [purs-nix/purs-nix#40]
When these `dependencies` are generated, an extra whitespace character is included at the end, i.e. after `transformers`:
```
        dependencies =
          [ "basic-auth" "bucketchain" "effect" "maybe" "prelude" "transformers" 
          ];
```

I think this extra character exists for every `dependencies` list in `official-package-set/default.nix`

**Comment by ursi** [comment]
I am aware of this, I just haven't changed it because it seems inconsequential. Regarding why it was written that way in the first place, I am assuming it was because it was easier.

**Comment by ursi** [comment]
I have added a formatter to the project now, so this is no longer the case
