### ISSUE TITLE
Unexpected different value for FFI deps

### ISSUE THREAD

**Issue by klarkc** [purs-nix/purs-nix#44]
I have found a really weird bug when trying to use `instanceof` on class instances imported from shared FFI deps. This is package config:

```nix
{
   # ...
   info = {
      #...
      foreign =
        let
          ffi = [
            # ...
            "Ctl.Internal.Types.BigNum"
            "Ctl.Internal.Types.Int"
            # ...
          ];
        in
        pkgs.lib.attrsets.genAttrs ffi (_: { inherit node_modules; });
#...
```

`node_modules` is a derivation with installed dependencies.

`Ctl.Internal.Types.BigNum` imports a class from `@emurgo/cardano-serialization-lib-nodejs`, the same happens in `Ctl.Internal.Types.Int`. Internally the class (BigNum in my case, but there are more classes) asserts that the given instance is actually from the expected class, but it is not, throwing an error.

The issue is caused by a conflict in the module resolution algorithm used by node.js. When multiple versions of a module are installed in different directories, node.js will choose the version with the highest precedence in the search path. However, if a module is imported from one path, and then later the same module is imported from a different path, node.js may not recognize the two imports as referring to the same module, even if the module content is identical. As a result, classes defined in the module may not be recognized as constructors when called from other modules. (In my case a value instance of the shared lib BigNum, which  is being passed from `Int` to `BigNum`).

I did some test manually going in the nix store file and changing the import to the same absolute path, and it fixed the error.

This is causing errors all the way in my application, I am trying to figure out how to deal with that. Any ideas?

**Comment by klarkc** [comment]
This is how the purs-nix derivation is being built:

```
 ~/Sources/LovelaceAcademy/modules/M09-going-live/dapp (main +)$ tree -d /nix/store/y16j5vhimq93xsd62fs3pvrz9qndhp3j-all-deps+modules+test-modules+foreign/Ctl.Internal.Types.*
...
/nix/store/y16j5vhimq93xsd62fs3pvrz9qndhp3j-all-deps+modules+test-modules+foreign/Ctl.Internal.Types.BigNum
└── node_modules -> /nix/store/5wr5n9cd4l6bkr6qfmrskphbncvh19xc-cardano-transaction-lib-3.0.0/node_modules
...
/nix/store/y16j5vhimq93xsd62fs3pvrz9qndhp3j-all-deps+modules+test-modules+foreign/Ctl.Internal.Types.Int
└── node_modules -> /nix/store/5wr5n9cd4l6bkr6qfmrskphbncvh19xc-cardano-transaction-lib-3.0.0/node_modules
...

6 directories
```

**Comment by klarkc** [comment]
Instead of duplicating symlinks of node_modules on each purs module, I have used the install hook to add node_modules in the root folder of the package I'm building

```nix
{
   # ...
   info = {
      #...
      install = ''
        mkdir $out
        for entry in $src/src/*; do
          link=$(basename "$entry")
          ln -s "$entry" "$out/$link"
        done
        ln -s ${node_modules} $out/node_modules
      '';
# ...
```

It works creating a shared node_modules in the built package, but I believe it is discarded somewhere here in the final derivation

https://github.com/purs-nix/purs-nix/blob/5d0a08d3f708bc5ebd72908a21559733e12fd671/purs-nix.nix#L149-L168

**Comment by ursi** [comment]
Is the not-working code public? I would really like to take a look at it. If not, any chance you could whip up a minimal example?

**Comment by klarkc** [comment]
@ursi https://github.com/klarkc/purs-nix/commit/00b112866a385340a30b299344dc1cd5db2e3273

**Comment by ursi** [comment]
Not using `--preserve-symlinks` with esbuild fixes the issue, for you example at least. Unfortunately, it causes other builds to fail. So I'll have to see what can be done.

**Comment by klarkc** [comment]
@ursi the workaround I made was not working with purs-nix command (purs-nix compile and test). 78c4007f84923dc1191a86ab136db5ccd98a9f02 fixed it and added a new feature: `info.foreign` can be used to import modules from a derivation. It is not optimal but it works for my use case: LovelaceAcademy/ctl-nix#34 and LovelaceAcademy/nix-templates#72.

**Comment by ursi** [comment]
what I'm planning on doing is changing foreign code to only work for modules in a particular packages. in other words, you can't add a foreign code for BigInt in your project directly. This not not a problem however, because we have the overlays system, so it just means you need make an overlay that uses a version of `BigInt` with your foreign additions, which will not be hard to set up. Doing this, I will build the foreign code with the packages, instead of adding it all at the end. This should allow me to not have to use `--prserve-symlinks` and then the `node_modules` directories that are the same will be treated as the same by esbuild.

**Comment by klarkc** [comment]
Let me see if I understand correctly. In the case of the example:

> @ursi [klarkc@00b1128](https://github.com/klarkc/purs-nix/commit/00b112866a385340a30b299344dc1cd5db2e3273)

You are attempting to fix the issue by not using or allowing foreign here:

https://github.com/purs-nix/purs-nix/blob/00b112866a385340a30b299344dc1cd5db2e3273/examples/issue-44/flake.nix#L45-L46

Is that correct? I am not sure how this will fix the issue. Perhaps when you have fixed it, you could provide the updated example in the repository?

**Comment by ursi** [comment]
No, that would still be allowed, because `Main` and `Alt` are modules in the project. What would not longer work would be going
```nix
foreign.Prelude = { inherit node_modules; }
```
because `Prelude` is a module in another package. Currently you can do that - add foreign code to any module from any package in the same spot. Which you might want to do if a dependency you need relies of foreign code. After the fix, the only way to add foreign code to a dependencies module will be to patch the dependency itself.

**Comment by klarkc** [comment]
I still can't see how it will fix the issue, but I hope it works :rofl:

**Comment by ursi** [comment]
not using `--preserve-symlinks` with esbuild fixes the issue, but with the way things currently work, not using `--preserve-symlinks` also creates a different issue. Restricting foreign dependencies in this way, I'm hoping, will allowing me to fix both of them.

**Comment by ursi** [comment]
@klarkc can you use the `docs-preview` branch in your project and tell me if it works?

**Comment by klarkc** [comment]
@ursi in the example it works, but my project is using the `ps-0.14` branch, do you plan to apply this change to this branch?

**Comment by ursi** [comment]
Yes, I will merge it now.

**Comment by ursi** [comment]
alright. let me know if it works for you.

**Comment by ursi** [comment]
I'm going to close this for now. Let me know if it didn't work.

**Comment by klarkc** [comment]
@ursi sorry for the late response. Yes, I'm now using it the way it was proposed, and yes, it fixed the issue.
