### ISSUE TITLE
Name collision when bundling with `purs-nix`

### ISSUE THREAD

**Issue by Soupstraw** [purs-nix/purs-nix#47]
I'm getting [a runtime error](https://github.com/purescript/purescript/issues/4503) with code generated via `purs-nix`, but not when running the same code in the online PureScript editor.

**Comment by Soupstraw** [comment]
I'm suspecting that the problem has something to do with the `bundle` command, the `eslint` step in particular

**Comment by Soupstraw** [comment]
Ok, I've managed to figure out what the issue is. I was supposed to add `type='module'` attribute to the `main.js` script tag in my html file.

**Comment by Soupstraw** [comment]
But it still might be worth pointing that out in the documentation

**Comment by ursi** [comment]
thanks for pointing out how old esbuild is. I should update nixpkgs in the flake. Do you have any recommendations on where to put that in the docs?

**Comment by ursi** [comment]
mmm I was hoping the nixpkgs update would be simple, but there is a nodejs 14 instance being built that I can't figure out how to get rid of, and I'm leaving for a week long trip tomorrow. I will have to get to it when I get back.

**Comment by Soupstraw** [comment]
I think it'd be a good idea to add an example project which doesn't run the purescript code on nodejs, but rather serves the resulting bundle from a HTTP server.

**Comment by ursi** [comment]
> mmm I was hoping the nixpkgs update would be simple, but there is a nodejs 14 instance being built that I can't figure out how to get rid of, and I'm leaving for a week long trip tomorrow. I will have to get to it when I get back.

https://github.com/nix-community/npmlock2nix/issues/189

**Comment by ursi** [comment]
nixpkgs has been updated. esbuild is now at version 0.19.11
