### ISSUE TITLE
`purs-nix run` fails, but `purs-nix bundle` then `node main.js` succeeds

### ISSUE THREAD

**Issue by edwardw** [purs-nix/purs-nix#48]
It involves the [`purescript-fetch`](https://github.com/rowtype-yoga/purescript-fetch) package and a simple one-liner:

```purescript
module Main where

import Prelude

import Effect (Effect)
import Effect.Aff (launchAff_)
import Effect.Class (liftEffect)
import Effect.Console (log)
import Fetch (fetch)

main :: Effect Unit
main =
  fetch "https://httpbin.org/get" {} >>= _.text >>= (log >>> liftEffect) # launchAff_
```

Either run the line in `purs-nix repl` environment or `purs-nix bundle` then `node main.js` does the right thing. But if trying to `purs-nix run`, it throws a runtime error:

```bash
file:///home/name/ws/fetch/output/Fetch.Core.Headers/foreign.js:2
  return new Headers();
  ^

ReferenceError: Headers is not defined
    at Module.unsafeNew (file:///home/edward/ws/fetch/output/Fetch.Core.Headers/foreign.js:2:3)
    at __do (file:///home/edward/ws/fetch/output/Fetch.Core.Headers/index.js:25:33)
    at Module.unsafePerformEffect (file:///home/edward/ws/fetch/output/Effect.Unsafe/foreign.js:2:10)
    at file:///home/edward/ws/fetch/output/Fetch.Core.Headers/index.js:24:30
    at file:///home/edward/ws/fetch/output/Fetch.Core.Headers/index.js:37:70
```

The `purescript-fetch` [document](https://pursuit.purescript.org/packages/purescript-fetch/3.0.0) does mention that fetch is a node feature after version `17.5`. But it should not have effect here since the default node version is now `18.*`. This is most bizarre.

**Comment by ursi** [comment]
Did you figure out what was going wrong?

**Comment by edwardw** [comment]
Unfortunately, no.

If it is only me, then it most likely had something to do with the wackiness of that particular direnv environment. It kept threw weird "/nix/store/.... : No such file or directory" error. Even a system-wide "sudo nix-store --repair --verify --check-contents" didn't do anything. I ended up nuking it.
