### ISSUE TITLE
`generate.sh` appears to be broken

### ISSUE THREAD

**Issue by peterbecich** [purs-nix/purs-nix#49]
On the latest commit:

```
$ ./generate.sh
fatal: couldn't find remote ref refs/tags/v0.15.14
error:
       … while evaluating the file '/home/peterbecich/nix/purs-nix/official-package-set/generate.nix':

       … while calling the 'foldl'' builtin

         at /nix/store/1krpkgd8fngc2pasx2nxhdaaz78ibb6w-source/lib/trivial.nix:63:8:

           62|     let reverseApply = x: f: f x;
           63|     in builtins.foldl' reverseApply val functions;
             |        ^
           64|

       … while calling the 'foldl'' builtin

         at /nix/store/1krpkgd8fngc2pasx2nxhdaaz78ibb6w-source/lib/trivial.nix:62:30:

           61|   pipe = val: functions:
           62|     let reverseApply = x: f: f x;
             |                              ^
           63|     in builtins.foldl' reverseApply val functions;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: program 'git' failed with exit code 128

```

I think it is related to PureScript v0.15.14 released a few days ago: https://github.com/purescript/purescript/releases

Thank you

**Comment by peterbecich** [comment]
I think this will fix it https://github.com/purs-nix/purescript-tools/pull/3

**Comment by ursi** [comment]
So this actually has to do with the purescript/metadata package. In the package set it says it's version 0.15.14, but when you go to it's repository, that tag doesn't exist.

**Comment by peterbecich** [comment]
Another good catch, thanks, will submit PR now: https://github.com/purescript/purescript-metadata

**Comment by JordanMartinez** [comment]
The `purescript-metadata` package exists IIRC so that Spago knows
- which compiler version a given package set works with
- what the latest compiler even is

This is not included in the compiler's `RELEASE_GUIDE.md` but should be. I know to do it but forgot about it this time. I was also wondering whether this was still needed due to the recent Registry work.

**Comment by ursi** [comment]
thanks @JordanMartinez :)
package set and compiler has been updated
