### ISSUE TITLE
request for clarification about why `modules` deprecated

### ISSUE THREAD

**Issue by peterbecich** [purs-nix/purs-nix#50]
The `modules` attribute set is deprecated:
https://github.com/purs-nix/purs-nix/blob/master/docs/derivations.md#modules-deprecated

Is it because `the modules.x API has been replaced with just x` , noted in this commit message? https://github.com/purs-nix/purs-nix/commit/99b26f51852279c2d4ce4103b24cb9cc036f57cc

Thank you

**Comment by ursi** [comment]
Yes, I guess I decided for one reason or another that passing the module name in as an argument was a better API.

**Comment by peterbecich** [comment]
Thanks, that helps me
