### ISSUE TITLE
feature request: specify PureScript package in Flake input

### ISSUE THREAD

**Issue by peterbecich** [purs-nix/purs-nix#53]
I have read the section "Modifying the Package Set": https://github.com/purs-nix/purs-nix/blob/master/docs/modifying-package-set.md#modifying-the-package-set

That works perfectly; used in this project, for example: https://github.com/peterbecich/halogen-chess/blob/b9a634d2bfe53628a92dd23b5898dc51fa7c6296/flake.nix#L58-L77

My feature request is a way to specify `src.git` with a Flake input.

Can this be replaced
```
"my.prelude" =
   { src.git =
       { repo = "https://github.com/me/prelude.git";
         rev = "0000000000000000000000000000000000000000";
       };

     info = ./package.nix;
   };
```

with something like

```
inputs = {
  .
  .
  .
  my-prelude.url = "github:me/prelude/0000000000000000000000000";
  .
  }
```
?

I have made one attempt at feeding this Flake input into `purs-nix.build`, but it did not work.

Thank you

**Comment by ursi** [comment]
let me know if this did not address your problem
