### ISSUE TITLE
broken link in documentation (package override)

### ISSUE THREAD

**Issue by michelrandahl** [purs-nix/purs-nix#54]
I am trying to figure out how to override the package `purescript-web-workers`, which seems to only be version 1.1.0 in the registry even though a later version 2.0.0 was released last year. I figured out how to override the dependency in a spago project, but I would prefer to use purs-nix.
I have read a bit around in the documentation and experimented a bit with my flake.nix, but still haven't figured out how to override the package. With everything I have tried, I am still at web-workers version 1.1.0.
This is where I came across a broken link: https://github.com/purs-nix/purs-nix/blob/master/docs/overriding-packages.md at https://github.com/purs-nix/purs-nix/blob/2aaba0f192df732d225d1d60b7f153fda46f1046/docs/purs-nix.md#L13

**Comment by ursi** [comment]
also, I if you want to put in a PR to add the updated version to the purs-nix package set, I will accept it :) https://github.com/purs-nix/purs-nix/blob/master/ps-pkgs.nix

**Comment by michelrandahl** [comment]
I successfully figured out how to override the package in my flake.nix
```
        purs-nix = inputs.purs-nix {
          inherit system;
          overlays =
            [ (self: super:
                { "web-workers" =
                    { src.git =
                         { repo = "https://github.com/purescript-web/purescript-web-workers.git";
                           rev = "063ea75658082b600926c11f1c8e13fe6e2c4924";
                         };
                      info = {
                        version = "2.0.0";

                        dependencies = [
                          "effect"
                          "foreign"
                          "functions"
                          "maybe"
                          "newtype"
                          "prelude"
                          "unsafe-coerce"
                          "web-events"
                        ];
                      };
                    };
                }
              )
            ];
        };
```
Separately I also attempted to add it to `ps-pkgs.nix`, but I could not figure out how to reference the package to test it out in my own flake.nix https://github.com/michelrandahl/purs-nix/commit/497a95ee74f21126ca334c7375e737c0b918c8ec
When trying to test it in my flake.nix, I had added a reference like this:
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    ps-tools.follows = "purs-nix/ps-tools";
    #purs-nix.url = "github:purs-nix/purs-nix/ps-0.15";
    purs-nix = {
      url = "github:michelrandahl/purs-nix/497a95ee74f21126ca334c7375e737c0b918c8ec";
    };
    utils.url = "github:numtide/flake-utils";
  };
```
But I could not figure out how to proceed from there. All my attempts ended with `purs-nix packages` reporting `web-workers: 1.1.0`. Perhaps there is a full flake.nix example somewhere of how to reference a package defined in ps-pkgs.nix?

**Comment by ursi** [comment]
Ah, what's going wrong is the version is getting overridden by the version in the official package set at the end of the file https://github.com/purs-nix/purs-nix/blob/8caa40f7fe69b9fcd05baae04c4ec9eb43953e2e/ps-pkgs.nix#L63
If you add your override *after* this line, it will be applied.
